app/Http/routes.php
<?php
Route::group(['middleware' => ['web']], function ()
{
    //"middleware"=>['role:admin', 'auth']
    Route::group(["prefix"=>"admin", "namespace"=>"Admin", "middleware"=>['role:admin', 'auth']], function ()
    {
        Route::get('/', ['as'=>'admin.dashboard', "uses"=>'AdminController@index']);
        Route::resource('users', 'UsersController');
        Route::resource('groups', 'GroupsController');
        Route::resource('companies', 'CompaniesController');
    });

    Route::get('/', ['as'=>'home', 'uses'=>'HomeController@index']);
    Route::get('/about', ['as'=>'about', 'uses'=>'PagesController@about']);
    Route::get('/disclaimer', ['as'=>'disclaimer', 'uses'=> 'PagesController@disclaimer']);
    Route::auth();
    Route::get('confirm', ['as'=>'auth.confirm', 'uses'=>'Auth\AuthController@confirm']);
    Route::get('auth/confirmation/{code}', ['as'=>"auth.confirmation", 'uses'=>'Auth\AuthController@getConfirmation']);
    Route::resource('announcements', 'AnnouncementsController');
    Route::resource('messages', 'MessagesController');
    Route::resource('posts', 'PostsController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('groups', 'GroupsController');
    Route::resource('groups.users', 'GroupUserController', ['only' => ['store', 'update','destroy']]);
    Route::resource('groups.children', 'GroupChildController', ['only'=>['store','update','destroy']]);
    Route::resource('groups.announcements', 'GroupAnnouncement');
    Route::resource('groups.posts', 'GroupPostController');
    Route::resource('myBooks', 'MyBookController');
    Route::resource('myBooks.profiles', 'MyBookProfileController', ['only'=>'store']);
    Route::resource('searches', 'SearchesController');
    Route::get('/{profiles}', ['as' => 'profiles', 'uses' => 'ProfilesController@show']);
    Route::resource('profiles', 'ProfilesController');
    Route::resource('profiles.categories', 'ProfileCategoryController');
    Route::resource('photos', 'PhotosController',['only'=>['store','update','destroy']]);
    Route::resource('users', 'UsersController');
    Route::resource('users.profiles', 'UserProfileController', ['only' => ['store', 'update', 'destroy']]);
});

Route::group(['middleware' => ['api','auth:api'], 'prefix'=>'api', 'namespace'=>"Api"], function ()
{
    Route::resource('visitors', 'VisitorsController');
    Route::resource('photos', 'PhotosController',['only'=>['store','update','destroy']]);
    Route::resource('categories', 'CategoriesController');
    Route::resource('profiles.photos', 'ProfilePhotoController');
    Route::resource('groups', 'GroupsController');
    Route::resource('groups.photos', 'GroupPhotoController');
    Route::resource('groups.users', 'GroupUserController');
    Route::resource('profiles.categories', 'ProfileCategoryController');
    Route::resource('users.profiles', 'UserProfileController', ['only' => ['store', 'update', 'destroy']]);
});

routes/web.php
<?php

use App\Http\Controllers\MyBookProfileController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Mcamara\LaravelLocalization\LaravelLocalization;


$laravelLocalization = new LaravelLocalization();
Route::group(["prefix"=>"admin", 'as' => 'admin.', "namespace"=>"Admin", "middleware"=>['role:SuperAdmin', 'auth']], function ()
{
    Route::get('/', ['as'=>'dashboard', "uses"=>'AdminController@index']);
    Route::get('/home', ['as'=>'home', "uses"=>'AdminController@index']);
    Route::resource('users', 'UsersController');
    Route::resource('groups', 'GroupsController');
    Route::resource('companies', 'CompaniesController');
});

Route::group([
    'prefix' => $laravelLocalization->setLocale(),
    "middleware" => [
        'localeSessionRedirect',
        'localizationRedirect',
        'localeViewPath'

    ]
], function()
{
    Route::group(["middleware"=>['auth', 'verified', 'user.has.profile']], function ()
    {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::resource('posts', 'PostsController');
        Route::resource('myBooks', 'MyBookController');
        Route::resource("myBooks.profiles", MyBookProfileController::class);
        Route::resource('users', 'UsersController');
        Route::resource('categories', 'CategoriesController');
        Route::resource('myBooks.profiles',"MyBookProfileController")->only(['store']);
        Route::resource('profiles.announcements', 'ProfileAnnouncementController');
        Route::resource('announcements', 'AnnouncementsController');
        Route::resource('groups.announcements', 'GroupAnnouncementController');
        Route::resource('groups.users', "GroupUserController");
        Route::resource('groups.roles', "GroupRoleController");
        Route::resource('companies.photos', "CompanyPhotoController");
        Route::resource('companies.backgrounds', "CompanyBackgroundController");
        Route::resource('companies.hours', "CompanyHourController");
        Route::resource("companies.announcements", "CompanyAnnouncementController");
        Route::resource("companies.tags", "CompanyTagController");
        Route::resource("companies.messages", "CompanyMessageController");

    });


    Route::get('/', function () {
        return view('welcome');
    });
    Auth::routes(['verify'=>true]);
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/disclaimer', 'PagesController@disclaimer');
    Route::get('/about', 'PagesController@about');
    Route::resource('groups', 'GroupsController');
    Route::resource('searches', 'SearchesController');
    Route::resource('profiles', 'ProfilesController');
    Route::get('/{profile}', ['as' => 'profile', 'uses' => 'ProfilesController@show']);



});

resources/views/admin/home.blade.php
@extends('admin.layout.app')
@section('header')
    <!-- START Language list-->
    <div class="pull-right">
        <div class="btn-group">
            <button type="button" data-toggle="dropdown" class="btn btn-default">English</button>
            <ul role="menu" class="dropdown-menu dropdown-menu-right animated fadeInUpShort">
                <li><a href="#" data-set-lang="en">English</a>
                </li>
                <li><a href="#" data-set-lang="es">Spanish</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- END Language list    -->
    Dashboard
    <small data-localize="dashboard.WELCOME"></small>
@stop
@section('content')
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <!-- START widget-->
            <div class="panel widget bg-primary">
                <div class="row row-table">
                    <div class="col-xs-4 text-center bg-primary-dark pv-lg">
                        <em class="fa fa-user fa-3x"></em>
                    </div>
                    <div class="col-xs-8 pv-lg">
                        <div class="h2 mt0">{{ $users }}</div>
                        <div class="text-uppercase">Users</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <!-- START widget-->
            <div class="panel widget bg-purple">
                <div class="row row-table">
                    <div class="col-xs-4 text-center bg-purple-dark pv-lg">
                        <em class="fa fa-users fa-3x"></em>
                    </div>
                    <div class="col-xs-8 pv-lg">
                        <div class="h2 mt0"> {{ $groups }}
                        </div>
                        <div class="text-uppercase">Groups</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <!-- START widget-->
            <div class="panel widget bg-green">
                <div class="row row-table">
                    <div class="col-xs-4 text-center bg-green-dark pv-lg">
                        <em class="fa fa-briefcase fa-3x"></em>
                    </div>
                    <div class="col-xs-8 pv-lg">
                        <div class="h2 mt0">0</div>
                        <div class="text-uppercase">Companies</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <!-- START widget-->
            <!-- START date widget-->
            <div class="panel widget">
                <div class="row row-table">
                    <div class="col-xs-4 text-center text-info">
                        <!-- Bar chart-->
                        <div data-sparkline=""
                             data-bar-color="#5d9cec"
                             data-height="20"
                             data-bar-width="3"
                             data-bar-spacing="2"
                             data-values="5,9,4,1,3,4,7,5"
                        ></div>
                    </div>
                    <div class="col-xs-8 pv-lg">
                        <h4 class="h2 mt0">10</h4>
                        <div class="text-uppercase">Visitors</div>
                    </div>
                </div>
            </div>
            <!-- END date widget    -->
        </div>
    </div>
    <div class="row">
        <!-- START dashboard main content-->
        <div class="col-lg-12">
            <!-- START chart-->
            <div class="row">
                <div class="col-lg-12">
                    <!-- START widget-->
                    <div id="panelChart9" class="panel panel-default panel-demo">
                        <div class="panel-heading">
                            <a href="#"
                               data-tool="panel-refresh"
                               data-toggle="tooltip"
                               title="Refresh Panel" class="pull-right">
                                <em class="fa fa-refresh"></em>
                            </a>
                            <a href="#" data-tool="panel-collapse" data-toggle="tooltip" title="Collapse Panel" class="pull-right">
                                <em class="fa fa-minus"></em>
                            </a>
                            <div class="panel-title">Inbound visitor statistics</div>
                        </div>
                        <div class="panel-body">
                            <div class="chart-spline flot-chart" data-url="{{ route('api.visitors.index', ['api_token'=>Auth::user()->api_token]) }}"></div>
                        </div>
                    </div>
                    <!-- END widget-->
                </div>
            </div>
        </div>
        <!-- END dashboard main content-->
        <!-- START dashboard sidebar-->
        <!-- END dashboard sidebar-->
    </div>
@stop